export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  CATALOG: '/catalogo',
  ORDER_DETAIL: (id: string) => `/orders/${id}`,
  ORDERS: '/orders',
  CART: '/cart',
  CHECKOUT: '/checkout',
  PRODUCT_DETAIL: (id: string) => `/productos/${id}`,
  REVIEWS: '/reviews',
} as const;
